name: toddw
favicon: null
layout_spectrum: 1
typography_spectrum: 0.2080537904985249
title: Todd Site
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#48465b'
    - '#090909'
    - '#25252f'
    - '#8b8683'
    - '#8b5a4e'
  brandStrength: 0.1875
  lightness: 0.1182399052195251
  saturation: 0.48132355278357863
  rhythmicContrast: 0.026703302981331944
purpose: []
